---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-config
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "coco-kbs.labels" . | nindent 4 }}
data:
  rvps.json: |
    {
        "storage": {
            "type": "LocalFs",
            "file_path": "/opt/confidential-containers/attestation-service/reference_values"
        }
    }