[package]
name = "kms"
version = "0.1.0"
edition = "2021"
authors = ["Alibaba Cloud"]
description = "KMS/Vault drivers for confidential computing"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
const_format = "0.2"
hex.workspace = true
log.workspace = true
prost.workspace = true
p12 = "0.6.3"
rand = "0.8"
ring = "0.17"
reqwest = { workspace = true, default-features = false, features = ["rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
url = "2.5.4"
yasna = "0.5.2"

[dev-dependencies]
rstest.workspace = true
tokio = { workspace = true, features = ["rt", "macros" ] }

[build-dependencies]
anyhow.workspace = true
tonic-build.workspace = true

[features]
default = []

[lib]
name = "kms"
path = "src/lib.rs"
